"use strict";

const {
	SMALL_LEAF_BUDGET,
	SINGLE_FN_BUDGET,
	CUMULATIVE_CALLER_BUDGET,
} = require("./constants");

const INSTRUCTION_REGEX =
	/@\s*(\d+)\s*:\s*([0-9a-fA-F ]+)\s+([A-Z][a-zA-Z0-9]+)(.*)/g;

/**
 * Parses raw Ignition bytecode disassembly for a single candidate function.
 *
 * @param {string} blockText - Output text containing the function's bytecode block.
 * @param {string} name - Candidate identifier name.
 * @returns {object} Candidate bytecode analysis result.
 */
function parseCandidateBlock(blockText, name) {
	if (!blockText) {
		return createErrorResult(name, "Missing bytecode block");
	}

	// If multiple functions appear in this block, isolate the target function block
	let targetBlock = blockText;
	const functionBlocks = blockText.split("[generated bytecode for function: ");
	if (functionBlocks.length > 2) {
		// Look for matching name, or fallback to the last compiled function in this window
		let found = null;
		for (let i = 1; i < functionBlocks.length; i++) {
			const b = functionBlocks[i];
			const fnName = b.match(/^([a-zA-Z0-9_$]+)/)?.[1];
			if (fnName === name) {
				found = b;
				break;
			}
		}
		targetBlock = found || functionBlocks[functionBlocks.length - 1];
	}

	const lengthMatch = targetBlock.match(/Bytecode length:\s*(\d+)/);
	const paramMatch = targetBlock.match(/Parameter count\s*(\d+)/);
	const regMatch = targetBlock.match(/Register count\s*(\d+)/);
	const frameMatch = targetBlock.match(/Frame size\s*(\d+)/);

	if (!lengthMatch) {
		return createErrorResult(name, "Bytecode length not found in output");
	}

	const bytes = Number.parseInt(lengthMatch[1], 10);
	const parameters = paramMatch ? Number.parseInt(paramMatch[1], 10) : 0;
	const registers = regMatch ? Number.parseInt(regMatch[1], 10) : 0;
	const frameSize = frameMatch ? Number.parseInt(frameMatch[1], 10) : 0;

	const instructions = [];
	const regex = new RegExp(INSTRUCTION_REGEX.source, "g");
	let match = regex.exec(targetBlock);
	while (match !== null) {
		instructions.push({
			offset: Number.parseInt(match[1], 10),
			hex: match[2].trim(),
			mnemonic: match[3],
			operands: match[4].trim(),
		});
		match = regex.exec(targetBlock);
	}

	const isSmall = bytes <= SMALL_LEAF_BUDGET;
	const isInlinable = bytes <= SINGLE_FN_BUDGET;

	let status;
	if (isSmall) {
		status = "SMALL (Boosted)";
	} else if (isInlinable) {
		status = "INLINABLE";
	} else {
		status = "OVERSIZED (Blocked)";
	}

	const callerBudgetPercent = `${((bytes / CUMULATIVE_CALLER_BUDGET) * 100).toFixed(1)}%`;

	return {
		name,
		bytes,
		parameters,
		registers,
		frameSize,
		isSmall,
		isInlinable,
		status,
		callerBudgetPercent,
		instructionCount: instructions.length,
		instructions,
	};
}

/**
 * Extracts and parses candidate blocks from delimited child process stdout using sequential cursor scanning.
 *
 * @param {string} stdout - Full stdout stream from re-executed child process.
 * @param {string[]} candidateKeys - List of expected candidate names in suite order.
 * @returns {Array<object>} Array of parsed candidate result objects.
 */
function parseDelimitedOutput(stdout, candidateKeys) {
	const results = [];

	const startTokenPrefix = ["@@", "MICROBE_START", "@@:"].join("");
	const endTokenPrefix = ["@@", "MICROBE_END", "@@:"].join("");

	let cursor = 0;
	for (const key of candidateKeys) {
		const startToken = `${startTokenPrefix}${key}`;
		const endToken = `${endTokenPrefix}${key}`;

		const startIndex = stdout.indexOf(startToken, cursor);
		if (startIndex === -1) {
			results.push(createErrorResult(key, "Start marker not found"));
			continue;
		}

		const endIndex = stdout.indexOf(endToken, startIndex + startToken.length);
		if (endIndex === -1) {
			results.push(createErrorResult(key, "End marker not found"));
			continue;
		}

		const blockText = stdout.slice(startIndex + startToken.length, endIndex);
		results.push(parseCandidateBlock(blockText, key));
		cursor = endIndex + endToken.length;
	}

	return results;
}

function createErrorResult(name, errorReason) {
	return {
		name,
		bytes: null,
		parameters: null,
		registers: null,
		frameSize: null,
		isSmall: false,
		isInlinable: false,
		status: "ERROR",
		callerBudgetPercent: "N/A",
		instructionCount: 0,
		instructions: [],
		error: errorReason,
	};
}

module.exports = {
	parseCandidateBlock,
	parseDelimitedOutput,
};
